//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 ThermoXSDKSample.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_TICTYPE                     129
#define IDD_DIALOG_LOG                  131
#define IDD_DIALOG_MSCOMM               132
#define IDR_MENU_POP                    135
#define IDD_DIALOG_ADDPROBE             136
#define IDI_ICON_BLACK                  138
#define IDI_ICON_GRAY                   139
#define IDI_ICON_RED                    140
#define IDI_ICON_GREEN                  141
#define IDI_ICON_BLUE                   142
#define IDI_ICON_PINK                   143
#define IDI_ICON_PURPLE                 144
#define IDI_ICON_ORANGE                 145
#define IDI_ICON_YELLOW                 146
#define IDI_ICON_CYAN                   147
#define IDD_DIALOG_MASK                 152
#define IDI_ICON_POWERON                154
#define IDI_ICON_POWEROFF               155
#define IDI_ICON_PLAY                   156
#define IDD_CAMERA_PROPERTIES_DIALOG    157
#define IDI_ICON_PAUSE                  157
#define IDI_ICON_VIDEO                  158
#define IDI_ICON_FFC                    160
#define IDI_ICON_SAVEBMP                161
#define IDI_ICON_STOP                   162
#define IDI_ICON_METER                  165
#define IDD_DIALOG_RUNSTATUS            168
#define IDD_DIALOG_CALIB                169
#define IDD_DIALOG_SETTING              170
#define IDD_DIALOG_ORIG                 171
#define IDD_DIALOG_HEATDATA             172
#define IDD_DIALOG_REALIMAGE            173
#define IDD_DIALOG_TONG_CALIB           174
#define IDD_DIALOG_RADIAINFO            175
#define IDD_DIALOG_INPUT                176
#define IDC_COMBO_MAC                   1006
#define IDC_BUTTON_POWER_TEC2           1008
#define IDC_IPADDRESS                   1008
#define IDC_BUTTON_POWERON              1009
#define IDC_SG_EXPOSUREMIN_LABEL        1010
#define IDC_BUTTON_POWEROFF             1010
#define IDC_SG_EXPOSUREMAX_LABEL        1016
#define IDC_CHECK_MEDIANFILTER          1016
#define IDC_SG_GAINMIN_LABEL            1017
#define IDC_EDIT_LOG                    1018
#define IDC_COMBO_DATAANALYZER          1019
#define IDC_SG_GAIN_EDIT                1020
#define IDC_BUTTON_SAVETHEMALAVI        1022
#define IDC_BUTTON_SAVEANALYSIS         1023
#define IDC_BUTTON_FREEZE               1023
#define IDC_EDIT_FFCPEROID              1024
#define IDC_EDIT_FFCTEMPERATURE         1025
#define IDC_SG_GAINMAX_LABEL            1026
#define IDC_BUTTON_STARTPROCESS         1026
#define IDC_BUTTON_STOPPROCESS          1027
#define IDC_EDIT_TEC1                   1030
#define IDC_EDIT_TEC                    1030
#define IDC_EDIT_TEC2                   1031
#define IDC_EDIT_TEC1_T                 1032
#define IDC_EDIT_TEC_T                  1032
#define IDC_EDIT_MAXGREY                1033
#define IDC_EDIT_MINGREY                1034
#define IDC_EDIT_AVEGREY                1035
#define IDC_EDIT_TEC2_T                 1036
#define IDC_CHECK_NResponse             1037
#define IDC_SG_EXPOSURE_EDIT            1038
#define IDC_CHECK_BRESPONSE             1039
#define IDC_EDIT_ACCBASELINE            1040
#define IDC_SG_GAIN_FRAME               1041
#define IDC_SG_EXPOSURE_FRAME           1042
#define IDC_EDIT_SMTHRESPONSE           1044
#define IDC_EDIT_SMTHNETD               1045
#define IDC_BUTTON_POWER_SHUTTER        1046
#define IDC_BUTTON_POWER_LED            1048
#define IDC_BUTTON_POWER_CMOS           1049
#define IDC_BUTTON_SAVECMOSBMP          1052
#define IDC_BUTTON_SAVEDOWNSIZEDBMP     1053
#define IDC_SG_FRAMERATE_EDIT           1054
#define IDC_BUTTON_SAVRESPONSE          1055
#define IDC_BUTTON_SAVENETD             1056
#define IDC_EDIT_HLTHRESHOLD            1057
#define IDC_EDIT_DOWNSIZEFILE           1059
#define IDC_EDIT_CALIFILE               1060
#define IDC_BUTTON_POWER_TEC1           1065
#define IDC_MSCOMM                      1068
#define IDC_CHECK_SMOOTH                1069
#define IDC_BUTTON_SETCOMM              1070
#define IDC_COMBO_COM                   1071
#define IDC_EDIT_DISCARDCLOSE           1073
#define IDC_EDIT_DISCARDOPEN            1074
#define IDC_EDIT_SLOPETEC1              1075
#define IDC_EDIT_INTERTEC1              1076
#define IDC_EDIT_SLOPETEC2              1077
#define IDC_EDIT_INTERTEC2              1078
#define IDC_EDIT_SLOPEP1                1079
#define IDC_EDIT_INTERP1                1080
#define IDC_EDIT_SLOPEP2                1081
#define IDC_EDIT_INTERP2                1082
#define IDC_EDIT_SLOPEP3                1083
#define IDC_EDIT_INTERP3                1084
#define IDC_LIST_PROBE                  1085
#define IDC_EDIT_FPAX                   1086
#define IDC_EDIT_FPAY                   1087
#define IDC_COMBO_PROBESIZE             1088
#define IDC_EDIT_SAMPFREQ               1089
#define IDC_CHECK_PLOTCURVE             1091
#define IDC_COMBO_PROBECOLOR            1094
#define IDC_EDIT_NAME                   1095
#define IDC_EDIT_ALERM                  1096
#define IDC_BUTTON_SAVETEMP             1097
#define IDC_BUTTON_APPLY                1098
#define IDC_BUTTON_BROWSELUT            1099
#define IDC_BUTTON_BROWSECALI           1100
#define IDC_CHECK_HISTBALANCE           1100
#define IDC_EDIT_FOCALLEN               1102
#define IDC_EDIT_TAO                    1108
#define IDC_EDIT_VALID                  1111
#define IDC_BUTTON_SHUTTER              1112
#define IDC_COMBO_FILTER                1114
#define IDC_BUTTON_APPLYRESTART         1115
#define IDC_EDIT_FORECATEDNETD          1116
#define IDC_EDIT_MASKTEMPERATURE        1117
#define IDC_COMBO1                      1118
#define IDC_COMBO_IFILTER               1118
#define IDC_EDIT1                       1119
#define IDC_EDIT_EXPOSURESLOPE          1119
#define IDC_BUTTON1                     1120
#define IDC_BUTTON_SETEXPOSURE          1120
#define IDC_EDIT2                       1120
#define IDC_BUTTON_POWER                1121
#define IDC_EDIT3                       1121
#define IDC_BUTTON7                     1121
#define IDC_EDIT4                       1122
#define IDC_EDIT5                       1123
#define IDC_BUTTON_REFRESHGRAY          1124
#define IDC_EDIT6                       1124
#define IDC_CHECK_AUTOSAVERESPONSE      1125
#define IDC_EDIT7                       1125
#define IDC_EDIT_FFCFIXRATIO            1126
#define IDC_EDIT8                       1126
#define IDC_CHECK_AUTOENLAREG           1127
#define IDC_EDIT11                      1127
#define IDC_EDIT12                      1128
#define IDC_CHECK_FULLIMAGE             1129
#define IDC_EDIT15                      1129
#define IDC_EDIT16                      1130
#define IDC_BUTTON_EXPORTREG            1131
#define IDC_EDIT9                       1131
#define IDC_EDIT17                      1131
#define IDC_BUTTON_SCANVALIDGRAY        1132
#define IDC_EDIT10                      1132
#define IDC_EDIT22                      1132
#define IDC_EDIT13                      1133
#define IDC_EDIT23                      1133
#define IDC_BUTTON_SETCMOSREG           1134
#define IDC_EDIT14                      1134
#define IDC_EDIT24                      1134
#define IDC_CHECK_HIST                  1135
#define IDC_EDIT18                      1135
#define IDC_EDIT25                      1135
#define IDC_CHECK_PROBE                 1136
#define IDC_EDIT19                      1136
#define IDC_EDIT26                      1136
#define IDC_EDIT20                      1137
#define IDC_EDIT21                      1138
#define IDC_EDIT27                      1139
#define IDC_EDIT28                      1140
#define IDC_EDIT29                      1141
#define IDC_COMBO_TRANSIMGTYPE          1142
#define IDC_EDIT30                      1142
#define IDC_CHECK_REMOVEROWNOISE        1144
#define IDC_BUTTON_READ                 1156
#define IDC_EDIT_CAMERANAME             1159
#define IDC_BUTTON_DOWNLOADCALI         1162
#define IDC_BUTTON_EXITREMOTEAPP        1163
#define IDC_BUTTON_SETDEFAULT           1164
#define IDC_STATIC_CURVE                1165
#define IDC_BUTTON_SAVETEMPERATURE      1168
#define IDC_SLIDER_RDDE                 1179
#define IDC_STATIC_ROBOT_NETWORK        1186
#define IDC_STATIC_INFO1                1187
#define IDC_BUTTON2                     1187
#define IDC_STATIC_INFO2                1188
#define IDC_BUTTON3                     1188
#define IDC_STATIC_CAMERA_NETWORK       1189
#define IDC_BUTTON4                     1189
#define IDC_STATIC_INFO3                1190
#define IDC_BUTTON5                     1190
#define IDC_STATIC_INFO4                1191
#define IDC_LIST1                       1191
#define IDC_BUTTON6                     1191
#define IDC_STATIC_INFO5                1192
#define IDC_PROGRESS1                   1192
#define IDC_STATIC_INFO6                1193
#define IDC_LIST2                       1193
#define IDC_STATIC_INFO7                1194
#define IDC_STATIC_NO                   1194
#define IDC_STATIC_INFO8                1195
#define IDC_CHECK_VISION                1195
#define IDC_EDIT_CAMNAME2               1196
#define IDC_STATIC_INFO9                1196
#define IDC_STATIC_INFO10               1197
#define IDC_STATIC_INFO11               1198
#define IDC_STATIC_INFO12               1199
#define IDC_STATIC_INFO13               1200
#define IDC_EDIT_ROI_LEFT               1285
#define IDC_EDIT_ROI_TOP                1286
#define IDC_EDIT_ROI_WIDTH              1287
#define IDC_EDIT_RIO_HEIGHT             1288
#define ID_VIEW_CONTROLBAR              32771
#define ID_VIEW_LOGBAR                  32772
#define ID_VIEW_ADVCONFIG               32773
#define ID_POPMENU_ADDPROBE             32774
#define ID_POPMENU_PLOT                 32775
#define ID_POPMENU_SAVE                 32776
#define ID_POPMENU_EDIT                 32777
#define ID_POPMENU_DELETE               32778
#define ID_VIEW_CORRECTPARA             32783
#define ID_VIEW_MASKTEPERATURE          32785
#define ID_FILE_SAVEDDT                 32788
#define ID_FILE_LOADDDT                 32789
#define ID_VIEW_DATA                    32790
#define ID_32791                        32791
#define ID_VIEW_DATABAR                 32792
#define ID_VIEW_CALIB                   32794
#define ID_BUTTON32795                  32795
#define ID_VIEW_RADIACONFIG             32796
#define ID_32797                        32797
#define ID_VIEW_MENU_RADIAINFO          32798

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        179
#define _APS_NEXT_COMMAND_VALUE         32799
#define _APS_NEXT_CONTROL_VALUE         1196
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
